Refactor font-weight declarations.
studiometa/scss-toolkit pull request #18
Opened 2019-03-28 16:56 UTC by perruche

Resolve #16 

And reduce the number of lines to handle `font-weight`. 
I did not put all possible values as default : `$font-weights: (100, 200, 300, 400, 500, 600, 700, 800, 900) !default;` to avoid generating too much classes that won't be used in a project.

2019-03-28 17:22 UTC, lusimeon approved these changes

2019-03-29 10:15 UTC, titouanmathis requested changes
I added a proposition for what I think might be more interesting default values, but all good otherwise! 👍

2019-03-29 10:15 UTC, titouanmathis commented on src/framework/_typography.scss
> +$font-weights: (300, 500, 800) !default;
I would rather suggest the following default values : 

- 300: light
- 400: regular
- 700: bold

I think they are the most commonly used weights.

2019-03-29 10:31 UTC, titouanmathis requested changes
@perruche don't forget to update [the documentation](https://github.com/studiometa/scss-toolkit#framework_typographyscss) in the readme too 😉

2019-04-01 07:13 UTC, titouanmathis approved these changes
There is a small typo in the readme on line 442 (`--<breakpoin>` instead of `--<breakpoint>`), but it's all good otherwise!

Same thing as I told @lusimeon, it might be more interesting to close the PR in Github with big green button, I think closing the feature with Git Flow set the status of the PR to "closed" instead of "merged".

2019-04-01 08:45 UTC, merged