Add a base font-size variable to calculate type sizes
studiometa/scss-toolkit pull request #35
Opened 2019-08-08 09:45 UTC by lusimeon

Add a base font-size variable to calculate type sizes rather than use default size (16px)

2019-08-08 15:35 UTC, titouanmathis requested changes
Some documentation is missing and a condition is missing, seems good to me otherwise :)

2019-08-08 15:35 UTC, titouanmathis commented on src/framework/_typography.scss
> +html {
This declaration should be wrapped in a `@if $has-classes { ... }` condition to avoid duplicates in the compiled CSS.

2019-08-08 15:35 UTC, titouanmathis commented on readme.md
> +$font-size-base: 16px !default;
You should add the `$font-size-base` to the "Defintion" section above with a small description of its purpose.

2019-08-14 08:20 UTC, lusimeon commented
@titouanmathis If we merge this branch, spaces will be now evaluated based on `$font-size-base` instead of `16px` because of `$spaces-base: 8px / 16px * 1rem;`.
`1rem = $font-size-base` instead of `1rem = navigator font size` before.

Maybe we should change the `$spaces-base` to a single value like `$spaces-base: 8px;` and then in `_spaces.scss`: 
```scss
@function space($space) {
  ...
  // Return the value times the base value if our space is a number, or else we
  // return the whole value, allowing us to set `auto` in our `$spaces` list.
  @if (type-of($value) == 'number') {
    @return $value * ($spaces-base / $font-size-base * 1rem);
  } @else {
    @return $value;
  }
}
```

Unfortunaly, it will create a strong dependency between `_typography.scss` ($font-size-base) and `_spaces.scss` ($spaces-base) files…

2019-08-19 09:27 UTC, titouanmathis commented
> Unfortunaly, it will create a strong dependency between _typography.scss ($font-size-base) and _spaces.scss ($spaces-base) files…

@lusimeon I think it will be easier to maintain over time if we keep the typography and spaces configuration separate. But the specificity of this configuration should definitely be documented so that people are aware of it.

2019-08-19 09:35 UTC, titouanmathis commented
There is something troubling me in this PR. The ability to set the root font size on which all other sizes are based is definitely a good feature, but this SCSS toolkit CSS output only contains classes and has no side effect on HTML elements. So I think that setting the root font size directly on the `html` element might not be the best way to set it. 

Maybe we should just add a new `.type-root-size` class that sould be added to the `html` element on each project.

2019-08-19 19:54 UTC, titouanmathis commented
I am changing the base of this PR from the `develop` branch to the `release/3.0.0` branch in order to include this feature in the future v3.0.0 😉

2019-08-19 20:13 UTC, titouanmathis commented
I merge this PR to send it in the first beta release of the v3.0.0 😉

2019-08-19 20:14 UTC, merged